[project]
authors = [
    "Dan Allan <dallan@bnl.gov>",
    "Brigitta Sipőcz <brigitta.sipocz@gmail.com>",
    "Ross Barnowski <rossbar@caltech.edu>",
    "Kyle Sunden <git@ksunden.space>",
]
channels = ["conda-forge"]
description = "Add a short description here"
name = "executable-tutorials"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
build = { cmd = [
    "sphinx-build",
    ".",  # source directory
    "_build/html",  # target directory
    "-n",  # warn about missing references
    "-W",  # any warnings fail the build
    "-T",  # show tracebacks
    "--keep-going",  # do not stop on error
] }
clean = "rm -rf _build/*"
start = "jupyter lab"

[activation]
scripts = ["setup_jupyterlab_config.sh"]

[dependencies]
python = ">=3.11"
matplotlib-base = ">=3.9"
ipympl = ">=0.9"
jupyterlab = ">=4.2"
jupyterlab-myst = ">=2.4"

[pypi-dependencies]
sphinx = ">=8.0.2"
myst-nb = ">=1.1"
jupytext = ">=1.16"
sphinx-book-theme = ">=1.1"
sphinx-copybutton = ">=0.5"

[feature.jupyterlite.dependencies]
jupyterlab = "~=4.2.4"
jupyterlite-core = "==0.4.0"
jupyterlite-pyodide-kernel = "==0.4.1"
notebook = "~=7.2.1"

[environments]
jupyterlite = ["jupyterlite"]
